In [ ]:
#Images
    #Presented in pixel's 
    #2nd = Gray Scale = that is black and white 
    #binary = 0 and 1 
    #3d = (255, all RED, GREEN, BLUE when all are 255 = white (Red,Yellow then RED and GREEM =255 and BLUE = 0)

#What is Open CV :
    #(Launched by Intel in 1999, Written in C++ using python helps to use numpy operations)

    # You need to import open Cv Library


In [3]:
# Read the Images 

##imread used to read image

import cv2
imgfile = (r"C:\Users\Dipak\Desktop\Rea\priyanka.JFIF")
img = cv2.imread(imgfile,0)

##imshow to show image
cv2.imshow('comments',img) # here input has the images
#cv2.waitkey(0) #alllow u to press key for the image to go
#cv2.destroyAllWindows() # to destroy all open windows of images

##Shape of the image height,width
print ("Shape of the image",img.shape) 

##Print the height of the image
print ("Height",img.shape[0]) 

##Print the width of the image
print ("width",img.shape[1]) 

##To save the images here will save image as output.jpg
cv2.imwrite('output.jpg',input) # can read mulitple format jpg,png,vmps 

Shape of the image (201, 251)
Height 201
width 251


In [6]:
import cv2 as cv
imgfile = (r"C:\Users\Dipak\Desktop\Rea\priyanka.JFIF")
img = cv.imread(imgfile)

#Gray scaling images (Know as Black & White images)
    # cvtcolor is used for covering its acccepts the image and and color as BGR (not rbg))
gray_image = cv.cvtColor(img,cv.COLOR_ΒGR2GRAY) #first method
img = cv.imread(imgfile)
cv.imshow('comments',img)

#Gray Scaling images with putting 0 while reading
import cv2 as cv
imgfile = (r"C:\Users\Dipak\Desktop\Rea\priyanka.JFIF")
img = cv.imread(imgfile,0) # Second Method of Gray Scaling put 0 while reading the file
cv.imshow('comments',img)


AttributeError: module 'cv2.cv2' has no attribute 'COLOR_ΒGR2GRAY'

In [14]:
#Accessing pixel value at paticular location
import cv2 as cv
img =cv.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.JFIF")
gray_img=cv.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.JFIF",0)

#for colored image
R,G,B = img[10,50]
print(R,G,B)

#for Gray Image
print(gray_img[10,50]) # its 242 as its gray image


238 243 242
242


In [22]:
#Accessing the value at each pixel
print(gray_img.shape)

for i in range(gray_img.shape[0]):
    for j in range(gray_img.shape[1]):
        print("value of", i, "value of" ,j , gray_img[i][j])

(201, 251)
value of 0 value of 0 206
value of 0 value of 1 208
value of 0 value of 2 212
value of 0 value of 3 216
value of 0 value of 4 221
value of 0 value of 5 225
value of 0 value of 6 228
value of 0 value of 7 230
value of 0 value of 8 231
value of 0 value of 9 232
value of 0 value of 10 232
value of 0 value of 11 233
value of 0 value of 12 234
value of 0 value of 13 234
value of 0 value of 14 235
value of 0 value of 15 235
value of 0 value of 16 240
value of 0 value of 17 240
value of 0 value of 18 241
value of 0 value of 19 241
value of 0 value of 20 242
value of 0 value of 21 242
value of 0 value of 22 242
value of 0 value of 23 242
value of 0 value of 24 245
value of 0 value of 25 245
value of 0 value of 26 245
value of 0 value of 27 246
value of 0 value of 28 246
value of 0 value of 29 247
value of 0 value of 30 247
value of 0 value of 31 247
value of 0 value of 32 248
value of 0 value of 33 248
value of 0 value of 34 248
value of 0 value of 35 248
value of 0 value of 36 248


In [4]:
#Accessing the images using HSV
import cv2
#Image = (r"\C:\Users\Dipak\Desktop\Rea\priyanka.JFIF")
img =cv2.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.JFIF")
Hsv_image = cv2.cvtColor(img,cv2.COLOR_BGR2HSV) # here using BGRHSV
cv2.imshow("hsv image", Hsv_image)
cv2.imshow("Hue Chanell", Hsv_image[:, :,0])
cv2.imshow("Saturation Channel", Hsv_image[:, :, 1])
cv2.imshow("Value Channel", Hsv_image[:, :, 2])
cv2.waitKey(0)
#cv2.destroyAllWindows()


-1

In [21]:
#Split the images into different color index using split image cv2.split()
import numpy as np
import cv2
image =cv2.imread(r"C:\Users\Dipak\Desktop\Rea\IMG_6958.JPG")
print(image.shape)
B,G, R = cv2.split(image)
print(B)
cv2.imshow("Red",R) # All images would be gray as we have one dimension
cv2.imshow("Green",G)
cv2.imshow("Blue",B)
cv2.waitKey(0)


#Merge the image will get it to original image
Merged = cv2.merge([R,G,B])
cv2.imshow("Merged",Merged)
cv2.waitKey(0)

#Want to amplify blue color
Merged= cv2.merge([R+100,G,B])
cv2.imshow("merge the image and amplify blue by 100 max it can go to 255",Merged)
cv2.waitKey(0)


# Want to make image of Red, Green, & Blue 
#Let's create a matrix of zeros
#with dimensions of the image h x w
#here actually the chanel (3024, 4032, 3) that is 3 R,G,B so its one dimension we are converting to 3 channel but replacing the colors with zeros to convert so only one color is used and others are zeros
zeros = np.zeros(image.shape[:2], dtype ="uint8")
cv2.imshow("RED ONLY", cv2.merge([zeros,zeros,R]))
cv2.imshow("GREEN ONLY", cv2.merge([zeros,G,zeros]))
cv2.imshow("BLUE ONLY", cv2.merge([B,zeros,zeros]))
cv2.waitKey(0)

(3024, 4032, 3)
[[131 134 136 ...  83  84  79]
 [135 137 138 ...  77  78  76]
 [136 137 137 ...  81  80  79]
 ...
 [ 44  47  49 ...  68  78  75]
 [ 37  42  45 ...  68  76  79]
 [ 36  42  46 ...  74  80  84]]


-1

In [ ]:
#Histogram (23 unit)

import cv2
import numpy as np

# We need to create matplotlib to create our own histogram

image =cv2.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.JFIF")

#Need to use calcHist 

In [37]:
# Drawing images and Shapes using Open CV

import cv2
import numpy as np

#create a black image
image = np.zeros((512,512,3),np.uint8) # 512 is height and width and 3 is channel np.zeros is use to create array

#create a black square image this is gray scale as we not specifying 3 that is RGB but both look same
#image = np.zeros((512,512),np.uint8) # 512 is height and width and 3 is channel np.zeros is use to create array

#Draw a line over a black square
cv2.line(image,(0,0),(511,511),(100,0,0),5) #its bgr
#arguments image: is black square (0,0) is start position(511,511 is end position) (255,100,0 is RGB) and 5 is thickness of line
cv2.imshow("Blue Line", image)
cv2.waitKey(0)



#Draw a Rectangle over a black square
cv2.rectangle(image,(111,111),(300,300),(100,0,0),-1) # -1 fill's up the square
#arguments image: is black square (0,0) is start position (255,100,0 is RGB) and 5 is thickness of line
cv2.imshow("Rectangle", image)
cv2.waitKey(0)


#Draw a Rectangle over a black square here it takes point to start , radius, color and thickness or fill
cv2.circle(image,(111,111),100,(100,0,0),-1) # -1 fill's up the square
#arguments image is black square (0,0) is start position (255,100,0 is RGB) and 5 is thickness of line
cv2.imshow("Circle", image)
cv2.waitKey(0)


#Draw a Polygon
img = np.zeros((512,512,3),np.uint8)

# Define the points of polygon
pts = np.array([[10,50],[80,50],[100,50],[200,50],[300,50]], np.int32)

#Reshape our points in the form required by polylines
pts = pts.shape((-1,1,2))
cv2.polylines(img, [[pts]],true,(0,0,255,3)) # true polygon is closed or not
cv2.imshow("Polygon",img)
cv2.waitKey(0)

#Draw a Polygon
import numpy as np
import cv2
img = np.zeros((512,512,3),np.uint8)

# Define the points of polygon
pts = np.array([[10,50],[400,50],[90,20],[90,200]], np.int32)

#Reshape our points in the form required by polylines
pts = pts.reshape((-1,1,2))
cv2.polylines(img, [pts],True,(0,0,255),3) # true polygon is closed or not
cv2.imshow("Polygon",img)
cv2.waitKey(0)

-1

In [20]:
# Adding text to images
import numpy as np
import cv2
#Drawing a black image
img = np.zeros((512,512,3),np.uint8) 
cv2.putText(img,"Hello How r u",(40,50), cv2.FONT_HERSHEY_PLAIN,2, (100,170,0),3)
# text, start point, font, font size, color of font, thickness
cv2.imshow("Hello",img)
cv2.waitKey(0)

#Font's 
#FONT_HERSHEY_COMPLEX
#FONT_HERSHEY_PLAIN
#FONT_HERSHEY_COMPLEX_SMALL
#FONT_HERSHEY_TRIPLEX
#FONT_HERSHEY_DUPLEX
#FONT_HERSHEY_COMPLEX_SIMPLEX
#FONT_HERSHEY_SCRIPT_COMPLEX
#FONT_HERSHEY_SCRIPT_SIMPLEX




-1