In [ ]:
# Transformation of images
    #Affine
        #Affine includes : Scaling,Translation,Rotation
        #The line that are parallel images are also parallel in transformed images parllesim is always maintained
    #Non Affine
        #Know as Projective Transform and also called Homography
        #Does maintain collinearity and incidence
        #Does NOT preserve parallelism, length and angle
        #Very common in computer Vision
        #They orignate from different angle of cameras

In [ ]:
#Translation Matrix
    #    [1 0 Tx]
    # T=
    #   [0 1 Ty]
    #Transition means movving in one direction up, down, left ,right or even diagnolly
    # we use openCV function cv2.wrapAffine to implement this translation's
    # Tx means moving in x direction (Horizontally)
    #Tx means moving in x direction (Vertically)
    
    

In [13]:
import cv2
import numpy as np

img =cv2.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.jfif")

#store the height and weight of image
height,width =img.shape[:2] 
# this take only 0 and 1 that is height and width the amount of pixel to be moved

Quater_height,Quater_width = height/4,width/4 #that is tx and ty in translation matrix the amount of pixel to be moved

#Translation Matrix
T = np.float32([[1,0,Quater_height,],[0,1,Quater_width]])

print(T) # if u refer to forluma 1,0, tx that is x direction 0,1,ty that is y direction

img_trans =cv2.warpAffine(img, T,(width,height))
cv2.imshow("Translation",img_trans)
cv2.waitKey(0)


[[ 1.    0.   50.25]
 [ 0.    1.   62.75]]


-1

In [17]:
#Rotation of image
    #Rotation Matrix here titha that is 0 is the angle of rotation
    #    [cos0 - sin0]
#M =
    #    [sin0 - cos 0]
    
    
import cv2
import numpy as np

img =cv2.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.jfif")
height,width =img.shape[:2] 

rotation_matrix = cv2.getRotationMatrix2D((width/2,height/2),90,1) # here widht/2,height/2 is the center point of the image 90 is rotation angle that is anticlock wise 1 is the scaling factor
# here 1 for scaling so image is cut if u put .5 it will get whole image becoz height and width have change
print(rotation_matrix)
rotated_image = cv2.warpAffine(img, rotation_matrix ,(width,height)) # chaniging the h & W according to new may be tedious instead u can use transponse
cv2.imshow("Rotated Image",rotated_image)
cv2.waitKey(0)

[[ 6.123234e-17  1.000000e+00  2.500000e+01]
 [-1.000000e+00  6.123234e-17  2.260000e+02]]


-1

In [18]:
# The other method of rotation where it adujust the h & W Without cropping and no black space
import cv2
import numpy as np

img =cv2.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.jfif")
rotate_image = cv2.transpose(img)
cv2.imshow("Rotated Image with transpose",rotated_image)
cv2.waitKey(0)


-1

In [1]:
#Resizing and scaling and Interpolation
    #Resizing invloves interpolation
    #interpolation mean's when we resize how do we find the gap's betweeen pixels
    #Suppose Enlaging the image the gap between pixel how do we fill it or generate pixel
    #Types of interpolation

import cv2
import numpy as np

image = cv2.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.jfif")
#Scaling the orignal image
#BY DEFAULT IT USES INTER LINEAR
scaled_image = cv2.resize(image, None, fx =0.75,fy=0.75) # scaling fx fy 0.75 means 3 quater
cv2.imshow("Scaled Image",scaled_image)

#Lets double the sizof image
scaled_image_inter =cv2.resize(image, None, fx=2,fy=2, interpolation = cv2.INTER_CUBIC)
cv2.imshow("Scaled Image",scaled_image_inter)

#Lets Skew the size of the image
scaled_image_Area =cv2.resize(image, (400,900), interpolation = cv2.INTER_AREA) # 400,900 is the dimension we want (that is heigh and width)
cv2.imshow("Scaled Image",scaled_image_Area)


In [2]:
#IMAGE PYRAMIDS
    #Means shrinking and enlarging multiple copies of the image
    #Used in OBJECT DETECTION
    
import cv2
image = cv2.imread(r"C:\Users\Dipak\Desktop\Rea\priyanka.jfif")
smaller_image =cv2.pyrDown(image) # half of the orginal image
larger_image = cv2.pyrUp(image) # doubles the size

cv2.imshow("Orignal", image)
cv2.imshow("Smaller", smaller_image)
cv2.imshow("Larger", larger_image)
cv2.waitKey(0)
cv2.destroyAllWindows()